spring:
  #环境配置
  profiles:
    active: dev
    include: job
  #shardingSphere 配置
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
    sharding:
      default-data-source-name: ds0
      tables:
        t_request_log:
          actual-data-nodes: ds0.t_request_log_20200$->{6..7}
          logic-table: t_request_log
          table-strategy:
            standard:
              sharding-column: create_time
              precise-algorithm-class-name: com.ziroom.aquarius.common.vo.ShardingAlgorithm
    props:
      sql:
        show: false
  #redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    redisson:
      config: classpath:redisson.yaml

#用户自定义配置--rabbitMq相关
exchange:
  acquaris:
    sms: exchange.acquaris.sms
    mail: exchange.acquaris.mail

queue:
  acquaris:
    sms: exchange.acquaris.sms
    mail: exchange.acquaris.mail

#rocketMq整合
rocketmq:
  producer:
    group: finance

