elasticjob:
#  tracing:
#    type: RDB
  regCenter:
    serverLists: localhost:2181
    namespace: aquarius
  jobs:
#    myjob:
#      elasticJobClass: com.ziroom.aquarius.elasticjob.MyJob
#      cron: 0/5 * 1 * * ?
#      shardingTotalCount: 3
    scheduleJob:
      elasticJobClass: com.ziroom.aquarius.recoupjob.common.ScheduleJob
      cron: 0/10 * * * * ?
      shardingTotalCount: 3
