#数据库及连接池的配置
spring:
  profiles:
    active: dev
  datasource:
    #数据源基本配置
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      initialSize: 10
      maxActive: 20
      maxOpenPreparedStatements: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 1
      poolPreparedStatements: true
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: true
        url-pattern: /druid/*
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      validation-query-timeout: 500
      validationQuery: SELECT 1
  messages:
    encoding: UTF-8
    basename: i18n.login
  thymeleaf:
    cache: false
  resources:
    staticLocations: classpath:/resources/template

mybatis-plus:
  configuration:
    #mybatis plus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
